// Modules
import Head from 'next/head'
import Link from "next/link"
// Components
import { Layout } from "../layouts/layout"
// Styles

export const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Link
          href="/salary"
        >
          給与計算へ
        </Link>
      </Layout>
    </div>
  )
}

export default Home